// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4Point1_EF.Models;

namespace _4Point1_EF.Migrations
{
    [DbContext(typeof(CarsCodeFirstContext))]
    [Migration("20200918204640_UpdatedSeedData")]
    partial class UpdatedSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_4Point1_EF.Models.CodeFirstCar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnName("colour")
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ManufacturerID")
                        .HasColumnName("manufacturer_id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Odometer")
                        .HasColumnName("odometer")
                        .HasColumnType("int(10)");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnName("trim_level")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasName("FK_CodeFirstCar_Manufacturer");

                    b.ToTable("code_first_car");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 245327,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 2,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 155652,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 3,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 163293,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 4,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 133032,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 5,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 14223,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 6,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 174116,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 7,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 163182,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 8,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 3538,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 9,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 16827,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 10,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 134250,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 11,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 147251,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 12,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 52181,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 13,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 93552,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 14,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 99656,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 15,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 99553,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 16,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 134477,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 17,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 129015,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 18,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 214588,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 19,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 27271,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 20,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 270877,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 21,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 165629,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 22,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 22286,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 23,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 108418,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 24,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 259005,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 25,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 121177,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 26,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 176850,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 27,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 147751,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 28,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 152400,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 29,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 181501,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 30,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 276800,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 31,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 243678,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 32,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 59240,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 33,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 272086,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 34,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 287562,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 35,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 196929,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 36,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 118002,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 37,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 245526,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 38,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 287961,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 39,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 5995,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 40,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 208387,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 41,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 188999,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 42,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 37846,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 43,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 55018,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 44,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 46168,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 45,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 162379,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 46,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 25779,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 47,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 267312,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 48,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 256830,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 49,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 151372,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 50,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 245460,
                            TrimLevel = "Awesome"
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int?>("YearFounded")
                        .HasColumnName("year_founded")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Chevrolet",
                            YearFounded = 1911
                        },
                        new
                        {
                            ID = 2,
                            Name = "Ford",
                            YearFounded = 1903
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tesla"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Dodge"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Toyota",
                            YearFounded = 1937
                        },
                        new
                        {
                            ID = 6,
                            Name = "Honda",
                            YearFounded = 1946
                        },
                        new
                        {
                            ID = 7,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("_4Point1_EF.Models.CodeFirstCar", b =>
                {
                    b.HasOne("_4Point1_EF.Models.Manufacturer", "ManufacturerRed")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerID")
                        .HasConstraintName("FK_CodeFirstCar_Manufacturer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
